name: RichillCapital.Exchange.Web CI

on:
  push:
    branches:
      - master
      - dev

  pull_request:
    branches:
      - master
      - dev

env:
  NODE_VERSION: 22.x
  CONFIGURATION: development
  IMAGE: exchange-web
  APPLICATION_NAME: RichillCapital.Exchange.Web
  OUTPUT_DIRECTORY: ./dist

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Use Nerdbank.GitVersioning
      uses: dotnet/nbgv@master
      id: nbgv

    - name: Get Version
      id: version
      run: echo "::set-output name=version::$(git describe --tags --abbrev=0 || date +'%Y%m%d')-${{ steps.nbgv.outputs.GitCommitIdShort }}"

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: ${{ env.NODE_VERSION }}

    - name: Install dependencies
      run: npm i -g pnpm && pnpm i

    - name: Angular Build
      run: pnpm run build --configuration=${{ env.CONFIGURATION }} --verbose

    - name: Angular Tests
      run: pnpm run test --configuration=${{ env.CONFIGURATION }} --watch=false

    - name: Build Docker Image
      run: |
        docker build -t ${{ env.IMAGE }}:latest .

    - name: Upload Artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ env.APPLICATION_NAME }}-${{ steps.version.outputs.version }}
        path: ${{ env.OUTPUT_DIRECTORY }}
